### ISSUE TITLE
select2 box closes immediately on android

### ISSUE THREAD

**Issue by rompic** [ries-tech/redmine_improved_searchbox#9]
see
https://github.com/select2/select2/issues/2061

**Comment by bdemirkir** [comment]
I think it's better to disable select2 on mobile devices. Native selection interface is good enough.

**Comment by rompic** [comment]
sounds like a good idea

**Comment by rompic** [comment]
txh for the fast response. i hope i'll be able to look into it tomorrow

**Comment by rompic** [comment]
sorry this took longer than expected. works well on android and iphone
